name: Database Migration

on:
  push:
    branches: [ laravel ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create SQLITE File
      run: touch database/database.sqlite

    - name: Installation
      run: composer validate && composer install --quiet --no-dev

    - name: Envrionment
      run: composer run-script post-root-package-install

    - name: Migration
      run: php artisan migrate
    
    - name: Seeding
      run: php artisan db:seed
  
    - name: Fake Users Factory
      run: php -r 'require("vendor/autoload.php");factory(App\User::class, 1000)->create();exit(1);';
