name: Database Migration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installation
      run: composer validate && composer install --no-dev
      
    - name: Envrionment
      run: composer run-script post-root-package-install
      
    - name: Change Database Driver
      run: php -r "$ct=array_map(function ($line){ if (preg_match('/DB_CONNECTION=/', $line)) { return 'DB_CONNECTION=sqlite'; } return $line; }, file('.env')); file_put_contents('.env',join(PHP_EOL,$ct));"
      
    - name: Create SQLITE File
      run: php -r "file_exists('database/database.sqlite') || file_put_contents('database/database.sqlite', '');"

    - name: Migration & Seeding
      run: php artisan migrate && php artisan db:seed

   
    
