name: Database Migration

on:
  push:
    branches: [ master, laravel ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create SQLITE File
      run: php -r "file_exists('database/database.sqlite') || file_put_contents('database/database.sqlite', '');"

    - name: Installation
      run: composer validate && composer install --no-dev
      
    - name: Envrionment
      run: composer run-script post-root-package-install
      
    - name: Migration & Seeding
      run: php artisan migrate && php artisan db:seed

   
    
