name: Tests

on:
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
  
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: achievement crm
        ports: 
          - 3306:3306

    steps:
    - uses: actions/checkout@v2

    - name: Installation
      run: composer validate && composer install --quiet

    - name: Envrionment
      run: composer run-script post-root-package-install && composer run-script post-create-project-cmd

    - name: Migration
      run: php artisan migrate
    
    - name: Seeding
      run: php artisan db:seed
    
    - name: PHPUnit Test
      run: vendor/bin/phpunit
