name: Tests

on:
  push:
    branches: [ laravel ]

jobs:
  test:

    runs-on: ubuntu-latest
  
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: achievement crm
        ports: 
          - 3306:3306

    steps:
    - uses: actions/checkout@v2

    - name: Installation
      run: |
        composer validate
        composer install
        # composer install --quiet

    - name: Envrionment
      run: |
        composer run-script post-root-package-install
        composer run-script post-create-project-cmd

    - name: Migration and Seeding
      run: |
        php artisan migrate
        php artisan db:seed

    - name: PHPUnit Test
      run: vendor/bin/phpunit

    - name: Create Composer.lock File
      env:
        GH_USER: skmetheloper
        GH_REPO: crm
        GH_BRANCH: heroku 
        GH_SECRET: ${{secrets.GH_SECRET}}
      run: |
        curl -X GET -L https://gist.githubusercontent.com/skmetheloper/be53670f94028a045523cea61c373cee/raw/gh-put-content.php > ./gh-put-content.php
        php ./gh-put-content.php file ./composer.lock
