name: Tests

on:
  push:
    branches: [ laravel ]

jobs:
  test:

    runs-on: ubuntu-latest
  
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: achievement crm
        ports: 
          - 3306:3306

    steps:
    - uses: actions/checkout@v2

    - name: Installation
      run: composer validate && composer install --quiet

    - name: Envrionment
      run: composer run-script post-root-package-install && composer run-script post-create-project-cmd

    - name: Migration
      run: php artisan migrate
    
    - name: Seeding
      run: php artisan db:seed
    
    - name: PHPUnit Test
      run: vendor/bin/phpunit

    - name: Create Composer.lock File
      env:
        GH_SECRET: ${{secrets.GH_SECRET}}
      run: php -r "passthru('curl -X PUT -d \"'.json_encode(['message'=>'Create composer.lock','content'=>base64_encode(file_get_contents('composer.lock'))]) . '\" https://skmetheloper:${{GH_SECRET}}@api.github.com/repos/skmetheloper/crm/contents/composer.lock?ref=heroku');"
